[package]
name = "snarkvm-console-account"
version = "0.9.11"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Account operations for a decentralized virtual machine"
license = "GPL-3.0"
edition = "2021"

[[bench]]
name = "account"
path = "benches/account.rs"
harness = false

[dependencies.snarkvm-console-network]
path = "../network"
version = "0.9.11"

[dependencies.snarkvm-console-types]
path = "../types"
version = "0.9.11"
default-features = false
features = [ "address", "field", "group", "scalar" ]

[dependencies.bs58]
version = "0.4"

[dev-dependencies.bincode]
version = "1.3"

[dev-dependencies.criterion]
version = "0.4.0"

[dev-dependencies.serde_json]
version = "1.0"

[features]
default = [
  "compute_key",
  "graph_key",
  "private_key",
  "signature",
  "view_key"
]
compute_key = [ "private_key" ]
graph_key = [ "private_key" ]
private_key = [ "compute_key" ]
signature = [ "compute_key" ]
view_key = [ ]
