[package]
name = "snarkvm-synthesizer"
version = "0.9.11"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Synthesizer for a decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [
  "compilers",
  "cryptography",
  "mathematics",
  "wasm",
  "web-programming"
]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2021"

[[bench]]
name = "block"
path = "benches/block.rs"
harness = false

[[bench]]
name = "coinbase_puzzle"
path = "benches/coinbase_puzzle.rs"
harness = false
required-features = [ "setup" ]

[features]
default = [ "parallel" ]
parallel = [
  "rayon",
  "snarkvm-fields/parallel",
  "snarkvm-utilities/parallel"
]
aleo-cli = [ ]
cuda = [ "snarkvm-algorithms/cuda" ]
setup = [ ]
timer = [ "aleo-std/timer" ]

[dependencies.circuit]
package = "snarkvm-circuit"
path = "../circuit"
version = "0.9.11"

[dependencies.console]
package = "snarkvm-console"
path = "../console"
version = "0.9.11"

[dependencies.snarkvm-algorithms]
path = "../algorithms"
version = "0.9.11"

[dependencies.snarkvm-curves]
path = "../curves"
version = "0.9.11"

[dependencies.snarkvm-fields]
path = "../fields"
version = "0.9.11"

[dependencies.snarkvm-utilities]
path = "../utilities"
version = "0.9.11"
default-features = false

[dependencies.aleo-std]
version = "0.1.15"
default-features = false

[dependencies.anyhow]
version = "1.0.66"

[dependencies.blake2]
version = "0.10"
default-features = false

[dependencies.colored]
version = "2"

[dependencies.indexmap]
version = "1.8"
features = [ "serde", "rayon" ]

[dependencies.once_cell]
version = "1.13"

[dependencies.parking_lot]
version = "0.12"

[dependencies.paste]
version = "1.0.9"

[dependencies.rand]
version = "0.8"

[dependencies.rayon]
version = "1"
optional = true

[dependencies.reqwest]
version = "0.11"
features = [ "blocking", "json" ]

[dependencies.serde]
version = "1.0"

[dependencies.serde_json]
version = "1.0"

[dependencies.tracing]
version = "0.1"

[dev-dependencies.console]
package = "snarkvm-console"
path = "../console"
features = [ "test" ]

[dev-dependencies.bincode]
version = "1.3"

[dev-dependencies.criterion]
version = "0.4.0"
